version: "3"
services:
  springapp:
    build: .
    container_name: springapp
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/Demo
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./ScriptCreateDB.sql:/docker-entrypoint-initdb.d/ScriptCreateDB.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=Demo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    restart: always
volumes:
  pgdata: